version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: sh -c "npm install && npm run start"
    volumes:
      - .:/edsegura/app
    ports:
      - "3000:3000"
    depends_on:
      - db
